---
abstract: 'gnuplot wrapper using temporary files'
author:
  - 'Toshio Ito <toshioito@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
  Module::Build::Prereqs::FromCPANfile: '0.02'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gnuplot-Builder-TempFile
no_index:
  directory:
    - t
    - xt
    - eg
    - inc
  file:
    - README.pod
requires:
  File::Spec: '0'
  File::Temp: '0'
  Gnuplot::Builder: '0.13'
  IPC::Open3: '0'
resources:
  bugtracker: https://github.com/debug-ito/Gnuplot-Builder-TempFile/issues
  repository: git://github.com/debug-ito/Gnuplot-Builder-TempFile.git
version: '0.03'
